site_name: criu
site_description: Easy process freeze & thaw
site_author: Nehal Patel
repo_url: https://github.com/habemus-papadum/criu
repo_name: criu

theme:
  name: "material"
  palette:
    primary: blue grey


nav:
  - Home: index.md
  - API: reference.md

# If you'd like to specify a separate docs directory, you can do so here
docs_dir: docs

# Plugins to enable
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_submodules: true
